sonar.projectKey=Simulador-de-Batalha-PokeSal
sonar.projectName=Simulador-de-Batalha-PokeSal
sonar.host.url=http://localhost:9000
sonar.sources=src
sonar.tests=test
sonar.java.binaries=out/quality/classes
sonar.java.test.binaries=out/quality/test-classes
sonar.java.test.libraries=out/quality/tools/junit-console.jar
sonar.sourceEncoding=UTF-8
sonar.java.source=21
sonar.coverage.jacoco.xmlReportPaths=out/quality/jacoco.xml
sonar.junit.reportPaths=out/quality/junit
